// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Side

package io.socket.jeromq.pmodel;

public final class SideTest {
  private SideTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *买卖方向
   * </pre>
   *
   * Protobuf enum {@code Side}
   */
  public enum Side
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *允许使用别名，可以兼容老版本字段命名
     *    option allow_alias = true;
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>BUY = 1;</code>
     */
    BUY(1),
    /**
     * <code>SELL = 2;</code>
     */
    SELL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *允许使用别名，可以兼容老版本字段命名
     *    option allow_alias = true;
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>BUY = 1;</code>
     */
    public static final int BUY_VALUE = 1;
    /**
     * <code>SELL = 2;</code>
     */
    public static final int SELL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Side valueOf(int value) {
      return forNumber(value);
    }

    public static Side forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return BUY;
        case 2: return SELL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Side>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Side> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Side>() {
            public Side findValueByNumber(int number) {
              return Side.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SideTest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Side[] VALUES = values();

    public static Side valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Side(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Side)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\004Side*&\n\004Side\022\013\n\007UNKNOWN\020\000\022\007\n\003BUY\020\001\022\010\n\004" +
      "SELL\020\002B)\n\035com.kafang.jeromq.core.pmodelB" +
      "\010SideTestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
